spring:
  application:
    name: asset-management
  datasource:
    url: jdbc:h2:mem:greenko
    username: sa
    password:
#    url: jdbc:mysql://localhost:3306/greenko
#    username: root
#    password: Pass@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8000



