spring:
  application:
    name: asset-management
  datasource:
    url: jdbc:mysql://localhost:3306/greenko
    username: root
    password: Pass@123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8000

